import { Viewport, type Metadata } from 'next'
import { Roboto_Mono } from 'next/font/google'
import '../globals.css'

import { SanityLive } from '@/sanity/lib/live'
import Header from '@/components/Header'
import { getConfig } from '@/sanity/lib/config/getConfig'
import generateRssFeed from '@/utils/rss'
import Footer from '@/components/Footer'

const roboto = Roboto_Mono({
  subsets: ['latin'],
})

export async function generateMetadata(): Promise<Metadata> {
  const config = await getConfig();

  return {
    title: config?.title || 'Clerk Next.js Quickstart',
    description: config?.description || 'Generated by create next app',
    publisher: "Jan Walenda",
    creator: "Jan Walenda",
    keywords: [
      "Jan Walenda",
      "Portfolio",
      "Next.js",
      "Sanity"
    ],

    openGraph: {
      title: config?.title || 'Clerk Next.js Quickstart',
      description: config?.description || 'Generated by create next app',
      type: 'website',
      locale: 'en',
    },
    twitter: {
      title: config?.title || 'Clerk Next.js Quickstart',
      description: config?.description || 'Generated by create next app',
      card: 'summary_large_image',
    },

  }
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  colorScheme: 'light dark',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const config = await getConfig();

  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased relative`}>
        {/* Animated gradient background */}
        {config && <Header config={config} />}
        <main id="content" className="bg-base-100 elative shadow-xl">{children}</main>
        {config && <Footer config={config} />}
        <SanityLive />
      </body>
    </html>
  )
}