import { Viewport, type Metadata } from 'next'
import { Roboto_Mono } from 'next/font/google'
import '../globals.css'
import { SanityLive } from '@/sanity/lib/live'
import Header from '@/components/Header'
import { getConfig } from '@/sanity/lib/config/getConfig'
import Footer from '@/components/Footer'
import CommandMenu from '@/components/CommandMenu'
import { getAllPosts } from '@/sanity/lib/blog/getAllPosts'
import { getAllPages } from '@/sanity/lib/page/getAllPages'
import WinterSeasonEvent from '@/components/WinterSeasonEvent'
import { draftMode } from 'next/headers'
import { VisualEditing } from 'next-sanity/visual-editing'
import { DisableDraftMode } from '@/components/DisableDraftMode'

const roboto = Roboto_Mono({
  subsets: ['latin'],
})

export async function generateMetadata(): Promise<Metadata> {
  const config = await getConfig();

  return {
    title: config?.title || 'Clerk Next.js Quickstart',
    description: config?.description || 'Generated by create next app',
    publisher: "Jan Walenda",
    creator: "Jan Walenda",
    icons: {
      icon: '/favicon.png',
    },
    keywords: [
      "Jan Walenda",
      "Portfolio",
      "Next.js",
      "Sanity"
    ],

    openGraph: {
      title: config?.title || 'Next.js Quickstart',
      description: config?.description || 'Generated by create next app',
      type: 'website',
      locale: 'en',
    },
    twitter: {
      title: config?.title || 'Next.js Quickstart',
      description: config?.description || 'Generated by create next app',
      card: 'summary_large_image',
    },

  }
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  colorScheme: 'light dark',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const config = await getConfig();
  const posts = await getAllPosts();
  const pages = await getAllPages();

  return (
    <html lang="en" data-theme="light">
      <body className={`${roboto.className} antialiased relative`}>
        {/* Animated gradient background */}
        {config && <Header config={config} />}
        <WinterSeasonEvent />
        <CommandMenu pages={pages} posts={posts} />
        <main id="content"
          className="
            bg-base-100 
            relative 
            border-b 
            border-b-base-content 
            flex 
            flex-col 
            items-center 
            justify-center 
            min-h-screen
          ">
          {children}
        </main>
        {config && <Footer config={config} />}
        <SanityLive />
        {(await draftMode()).isEnabled && (
          <>
            <DisableDraftMode />
            <VisualEditing />
          </>
        )}
      </body>
    </html>
  )
}