/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type LinkReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "link";
};

export type CtaSection = {
  _type: "ctaSection";
  title?: string;
  subtitle?: string;
  primaryCta?: LinkReference;
  secondaryCta?: LinkReference;
};

export type Technology = {
  _type: "technology";
  name?: string;
  icon?: Icon;
  level?: "Beginner" | "Intermediate" | "Advanced" | "Expert";
  experience?: string;
  projects?: Array<string>;
};

export type Service = {
  _type: "service";
  title?: string;
  description?: string;
  icon?: Icon;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type HomepageHero = {
  _type: "homepageHero";
  badgeEnabled?: boolean;
  badgeText?: string;
  title?: string;
  subtitle?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryCta?: LinkReference;
  secondaryCta?: LinkReference;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSection?: HomepageHero;
  servicesTitle?: string;
  servicesSubtitle?: string;
  services?: Array<
    {
      _key: string;
    } & Service
  >;
  techStackTitle?: string;
  techStackSubtitle?: string;
  techStack?: Array<
    {
      _key: string;
    } & Technology
  >;
  selectedWorkTitle?: string;
  selectedWorkSubtitle?: string;
  selectedWorkCount?: number;
  ctaSection?: CtaSection;
  pageBuilder?: PageBuilder;
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & Hero)
  | ({
      _key: string;
    } & SplitImage)
  | ({
      _key: string;
    } & Features)
  | ({
      _key: string;
    } & Faqs)
  | ({
      _key: string;
    } & Grid)
  | ({
      _key: string;
    } & TextBlock)
>;

export type Icon = {
  _type: "icon";
  name?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SeasonEvent = {
  _id: string;
  _type: "seasonEvent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  message?: string;
  id?: string;
  startDate?: string;
  endDate?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: Array<string>;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  ogTitle?: string;
  ogDescription?: string;
  twitterCard?: "summary" | "summary_large_image" | "app" | "player";
  twitterTitle?: string;
  twitterDescription?: string;
  twitterImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  canonicalUrl?: string;
  noIndex?: boolean;
  noFollow?: boolean;
};

export type FooterColBuilder = {
  _type: "footerColBuilder";
  title?: string;
  links?: Array<
    {
      _key: string;
    } & LinkReference
  >;
};

export type CardReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "card";
};

export type Grid = {
  _type: "grid";
  title?: string;
  components?: Array<
    {
      _key: string;
    } & CardReference
  >;
};

export type TextBlock = {
  _type: "textBlock";
  title?: string;
  text?: BlockContent;
};

export type Card = {
  _id: string;
  _type: "card";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  action?: Array<
    {
      _key: string;
    } & LinkReference
  >;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
  seo?: Seo;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & Code)
  | ({
      _key: string;
    } & Callout)
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: PageBuilder;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: Seo;
};

export type Features = {
  _type: "features";
  title?: string;
  features?: Array<{
    title?: string;
    text?: string;
    _type: "feature";
    _key: string;
  }>;
};

export type FaqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faq";
};

export type Faqs = {
  _type: "faqs";
  title?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  body?: BlockContent;
};

export type Hero = {
  _type: "hero";
  title?: string;
  variant?:
    | "primary"
    | "secondary"
    | "neutral"
    | "accent"
    | "info"
    | "success"
    | "warning"
    | "error"
    | "base";
  text?: BlockContent;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Link = {
  _id: string;
  _type: "link";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  url?: string;
  icon?: Icon;
};

export type SplitImage = {
  _type: "splitImage";
  orientation?: "imageLeft" | "imageRight";
  variant?:
    | "primary"
    | "secondary"
    | "neutral"
    | "accent"
    | "info"
    | "success"
    | "warning"
    | "error"
    | "base";
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  defaultSeo?: Seo;
  headerLinks?: Array<
    {
      _key: string;
    } & LinkReference
  >;
  headerLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  headerLogoAlt?: string;
  footerColumns?: Array<
    {
      _key: string;
    } & FooterColBuilder
  >;
};

export type Callout = {
  _type: "callout";
  tone?: "info" | "tip" | "warning";
  title?: string;
  body?: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | LinkReference
  | CtaSection
  | Technology
  | Service
  | SanityImageAssetReference
  | HomepageHero
  | Homepage
  | PageBuilder
  | Icon
  | SanityImageCrop
  | SanityImageHotspot
  | SeasonEvent
  | Seo
  | FooterColBuilder
  | CardReference
  | Grid
  | TextBlock
  | Card
  | AuthorReference
  | CategoryReference
  | Post
  | BlockContent
  | Slug
  | Author
  | Category
  | Page
  | Features
  | FaqReference
  | Faqs
  | Faq
  | Hero
  | Link
  | SplitImage
  | SiteSettings
  | Callout
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/blog/getAllPosts.ts
// Variable: GET_ALL_POSTS_QUERY_ASC
// Query: *[_type == "post"] | order(publishedAt asc)
export type GET_ALL_POSTS_QUERY_ASC_RESULT = Array<{
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
  seo?: Seo;
}>;

// Source: sanity/lib/blog/getAllPosts.ts
// Variable: GET_ALL_POSTS_QUERY_DESC
// Query: *[_type == "post"] | order(publishedAt desc)
export type GET_ALL_POSTS_QUERY_DESC_RESULT = Array<{
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
  seo?: Seo;
}>;

// Source: sanity/lib/blog/getPostBySlug.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[      _type == "post" && slug.current == $slug    ] | order(publishedAt asc)[0]
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
  seo?: Seo;
} | null;

// Source: sanity/lib/config/getConfig.ts
// Variable: GET_CONFIG_QUERY
// Query: *[    _type == "siteSettings"    && _id == "siteSettings"  ][0] {    ...,    headerLinks[]-> {      ...,      icon {        ...      }    },    footerColumns[] {      ...,      links[]-> {        ...,        icon {          ...        }      }    }  }
export type GET_CONFIG_QUERY_RESULT = {
  _id: "siteSettings";
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  defaultSeo?: Seo;
  headerLinks: Array<{
    _id: string;
    _type: "link";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    url?: string;
    icon: {
      _type: "icon";
      name?: string;
    } | null;
  }> | null;
  headerLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  headerLogoAlt?: string;
  footerColumns: Array<{
    _key: string;
    _type: "footerColBuilder";
    title?: string;
    links: Array<{
      _id: string;
      _type: "link";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: Slug;
      url?: string;
      icon: {
        _type: "icon";
        name?: string;
      } | null;
    }> | null;
  }> | null;
} | null;

// Source: sanity/lib/config/getLinks.ts
// Variable: GET_LINKS_QUERY
// Query: *[      _type == "link"    ] | order(name asc)
export type GET_LINKS_QUERY_RESULT = Array<{
  _id: string;
  _type: "link";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  url?: string;
  icon?: Icon;
}>;

// Source: sanity/lib/homepage/getHomepage.ts
// Variable: homepageQuery
// Query: *[_type == "homepage" && _id == "homepage"][0] {    heroSection {      badgeEnabled,      badgeText,      title,      subtitle,      image,      primaryCta-> {        title,        slug,        url,        icon      },      secondaryCta-> {        title,        slug,        url,        icon      }    },    servicesTitle,    servicesSubtitle,    services[] {      _type,      title,      description,      icon    },    techStackTitle,    techStackSubtitle,    techStack[] {      _type,      name,      icon,      level,      experience,      projects    },    selectedWorkTitle,    selectedWorkSubtitle,    selectedWorkCount,    ctaSection {      title,      subtitle,      primaryCta-> {        title,        slug,        url,        icon      },      secondaryCta-> {        title,        slug,        url,        icon      }    },    pageBuilder[] {      _key,      _type,      _type == "hero" => {        ...,      },      _type == "splitImage" => {        ...,      },      _type == "features" => {        ...,      },      _type == "faqs" => {        ...,        faqs[]->      },      _type == "grid" => {        ...,        components[]-> {          ...,          action[]->        }      },      _type == "textBlock" => {        ...,      }    }  }
export type HomepageQueryResult = {
  heroSection: {
    badgeEnabled: boolean | null;
    badgeText: string | null;
    title: string | null;
    subtitle: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    primaryCta: {
      title: string | null;
      slug: Slug | null;
      url: string | null;
      icon: Icon | null;
    } | null;
    secondaryCta: {
      title: string | null;
      slug: Slug | null;
      url: string | null;
      icon: Icon | null;
    } | null;
  } | null;
  servicesTitle: string | null;
  servicesSubtitle: string | null;
  services: Array<{
    _type: "service";
    title: string | null;
    description: string | null;
    icon: Icon | null;
  }> | null;
  techStackTitle: string | null;
  techStackSubtitle: string | null;
  techStack: Array<{
    _type: "technology";
    name: string | null;
    icon: Icon | null;
    level: "Advanced" | "Beginner" | "Expert" | "Intermediate" | null;
    experience: string | null;
    projects: Array<string> | null;
  }> | null;
  selectedWorkTitle: string | null;
  selectedWorkSubtitle: string | null;
  selectedWorkCount: number | null;
  ctaSection: {
    title: string | null;
    subtitle: string | null;
    primaryCta: {
      title: string | null;
      slug: Slug | null;
      url: string | null;
      icon: Icon | null;
    } | null;
    secondaryCta: {
      title: string | null;
      slug: Slug | null;
      url: string | null;
      icon: Icon | null;
    } | null;
  } | null;
  pageBuilder: Array<
    | {
        _key: string;
        _type: "faqs";
        title?: string;
        faqs: Array<{
          _id: string;
          _type: "faq";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          body?: BlockContent;
        }> | null;
      }
    | {
        _key: string;
        _type: "features";
        title?: string;
        features?: Array<{
          title?: string;
          text?: string;
          _type: "feature";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "grid";
        title?: string;
        components: Array<{
          _id: string;
          _type: "card";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          description?: string;
          mainImage?: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          action: Array<{
            _id: string;
            _type: "link";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            slug?: Slug;
            url?: string;
            icon?: Icon;
          }> | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "hero";
        title?: string;
        variant?:
          | "accent"
          | "base"
          | "error"
          | "info"
          | "neutral"
          | "primary"
          | "secondary"
          | "success"
          | "warning";
        text?: BlockContent;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | {
        _key: string;
        _type: "splitImage";
        orientation?: "imageLeft" | "imageRight";
        variant?:
          | "accent"
          | "base"
          | "error"
          | "info"
          | "neutral"
          | "primary"
          | "secondary"
          | "success"
          | "warning";
        title?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | {
        _key: string;
        _type: "textBlock";
        title?: string;
        text?: BlockContent;
      }
  > | null;
} | null;

// Source: sanity/lib/page/getAllPages.ts
// Variable: GET_ALL_PAGES_QUERY
// Query: *[_type == "page"]
export type GET_ALL_PAGES_QUERY_RESULT = Array<{
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: PageBuilder;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: Seo;
}>;

// Source: sanity/lib/page/getPageBySlug.ts
// Variable: GET_PAGE_DATA_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{      ...,      content[] {        _key,        _type,        _type == "hero" => {          ...,        },        _type == "splitImage" => {          ...,        },        _type == "features" => {          ...,        },        _type == "faqs" => {          ...,          faqs[]->        },        _type == "grid" => {          ...,          components[]-> {            ...,            action[]->,          }        },        _type == "textBlock" => {          ...,        }      }    }
export type GET_PAGE_DATA_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content: Array<
    | {
        _key: string;
        _type: "faqs";
        title?: string;
        faqs: Array<{
          _id: string;
          _type: "faq";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          body?: BlockContent;
        }> | null;
      }
    | {
        _key: string;
        _type: "features";
        title?: string;
        features?: Array<{
          title?: string;
          text?: string;
          _type: "feature";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "grid";
        title?: string;
        components: Array<{
          _id: string;
          _type: "card";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          description?: string;
          mainImage?: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          action: Array<{
            _id: string;
            _type: "link";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            slug?: Slug;
            url?: string;
            icon?: Icon;
          }> | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "hero";
        title?: string;
        variant?:
          | "accent"
          | "base"
          | "error"
          | "info"
          | "neutral"
          | "primary"
          | "secondary"
          | "success"
          | "warning";
        text?: BlockContent;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | {
        _key: string;
        _type: "splitImage";
        orientation?: "imageLeft" | "imageRight";
        variant?:
          | "accent"
          | "base"
          | "error"
          | "info"
          | "neutral"
          | "primary"
          | "secondary"
          | "success"
          | "warning";
        title?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | {
        _key: string;
        _type: "textBlock";
        title?: string;
        text?: BlockContent;
      }
  > | null;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: Seo;
} | null;

// Source: sanity/lib/seasonEvent/getActiveSeasonEvent.ts
// Variable: GET_ACTIVE_SEASON_EVENT_BY_ID
// Query: *[_type == "seasonEvent" && defined(_id) && id == $id][0]
export type GET_ACTIVE_SEASON_EVENT_BY_ID_RESULT = {
  _id: string;
  _type: "seasonEvent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  message?: string;
  id?: string;
  startDate?: string;
  endDate?: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post"] | order(publishedAt asc)\n': GET_ALL_POSTS_QUERY_ASC_RESULT;
    '\n  *[_type == "post"] | order(publishedAt desc)\n': GET_ALL_POSTS_QUERY_DESC_RESULT;
    '\n    *[\n      _type == "post" && slug.current == $slug\n    ] | order(publishedAt asc)[0]\n  ': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[\n    _type == "siteSettings"\n    && _id == "siteSettings"\n  ][0] {\n    ...,\n    headerLinks[]-> {\n      ...,\n      icon {\n        ...\n      }\n    },\n    footerColumns[] {\n      ...,\n      links[]-> {\n        ...,\n        icon {\n          ...\n        }\n      }\n    }\n  }\n': GET_CONFIG_QUERY_RESULT;
    '\n    *[\n      _type == "link"\n    ] | order(name asc)\n  ': GET_LINKS_QUERY_RESULT;
    '\n  *[_type == "homepage" && _id == "homepage"][0] {\n    heroSection {\n      badgeEnabled,\n      badgeText,\n      title,\n      subtitle,\n      image,\n      primaryCta-> {\n        title,\n        slug,\n        url,\n        icon\n      },\n      secondaryCta-> {\n        title,\n        slug,\n        url,\n        icon\n      }\n    },\n    servicesTitle,\n    servicesSubtitle,\n    services[] {\n      _type,\n      title,\n      description,\n      icon\n    },\n    techStackTitle,\n    techStackSubtitle,\n    techStack[] {\n      _type,\n      name,\n      icon,\n      level,\n      experience,\n      projects\n    },\n    selectedWorkTitle,\n    selectedWorkSubtitle,\n    selectedWorkCount,\n    ctaSection {\n      title,\n      subtitle,\n      primaryCta-> {\n        title,\n        slug,\n        url,\n        icon\n      },\n      secondaryCta-> {\n        title,\n        slug,\n        url,\n        icon\n      }\n    },\n    pageBuilder[] {\n      _key,\n      _type,\n      _type == "hero" => {\n        ...,\n      },\n      _type == "splitImage" => {\n        ...,\n      },\n      _type == "features" => {\n        ...,\n      },\n      _type == "faqs" => {\n        ...,\n        faqs[]->\n      },\n      _type == "grid" => {\n        ...,\n        components[]-> {\n          ...,\n          action[]->\n        }\n      },\n      _type == "textBlock" => {\n        ...,\n      }\n    }\n  }\n': HomepageQueryResult;
    '\n    *[_type == "page"]\n': GET_ALL_PAGES_QUERY_RESULT;
    '\n    *[_type == "page" && slug.current == $slug][0]{\n      ...,\n      content[] {\n        _key,\n        _type,\n        _type == "hero" => {\n          ...,\n        },\n        _type == "splitImage" => {\n          ...,\n        },\n        _type == "features" => {\n          ...,\n        },\n        _type == "faqs" => {\n          ...,\n          faqs[]->\n        },\n        _type == "grid" => {\n          ...,\n          components[]-> {\n            ...,\n            action[]->,\n          }\n        },\n        _type == "textBlock" => {\n          ...,\n        }\n      }\n    }\n': GET_PAGE_DATA_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "seasonEvent" && defined(_id) && id == $id][0]\n': GET_ACTIVE_SEASON_EVENT_BY_ID_RESULT;
  }
}
